apiversion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wishlist-app-ingress

  spec:
    rules:
      - http:
          - path: /
          pathType: Prefix
          backend:
            service:
              name: web-service
              port:
                targetPort: 80
                
