apiVersion: app/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 3
  selector: 
  matchLabels:
    component: wishlist-app
  template:
    metatdata:
      labels:
        component: wishlist-app
    spec:
      containers:
        - name: wishlist-app-container
        image: <later>
        ports:
        - containerport: 80
        env:
          - name: REDIS_HOST
          value: redis-service
          - name: REDIS_PORT
          value: '6379'
          - name: POSTGRES_HOST
          value: postgres-service
          - name: POSTGRES_USER
          value: hello_flask
          - name: POSTGRES_PORT
          value: '5432'
          - name: POSTGRES_DB
          value: hello_flask_db
          - name: PGPASSWORD
          valuefrom:
            secretKeyRef:
              name: wishlist-sceret
              key: PGPASSWORD

